parameters:
#    esi_salutations.example.class: Esi\SalutationsBundle\Example

services:
#    esi_salutations.example:
#        class: %esi_salutations.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
